name: CI

env:
  PROJECT_NAME: epymetheus

on:
  push:
  pull_request:
      branches:
      - main
      - master
      - release/*
  workflow_dispatch:

jobs:
  Test:
    name: Test
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8']

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install package
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install .

    - name: Install Pytest
      run: |
        python3 -m pip install pytest
        python3 -m pip install pytest-cov

    - name: Doctest
      run: |
        python3 -m pytest --cov=${PROJECT_NAME} tests
      if: always()

    - name: Pytest
      run: |
        python3 -m pytest --cov=${PROJECT_NAME} tests
      if: always()

    - name: CodeCov
      run: |
        python3 -m pip install codecov
        python3 -m codecov
    
    - name: Install Linters
      run: |
        python3 -m pip install flake8 black isort
      if: always()

    - name: Flake8
      run: |
        python3 -m flake8 ${PROJECT_NAME}
      if: always()

    - name: Black
      run: |
        python3 -m black --check ${PROJECT_NAME}
      if: always()

    - name: Isort
      run: |
        python3 -m isort --check --force-single-line-imports ${PROJECT_NAME}
      if: always()
